services:
  sub-store:
    image: xream/sub-store:http-meta
    container_name: sub-store
    restart: always
    volumes:
      - ./data/sub-store-data:/opt/app/data
    environment:
      - SUB_STORE_FRONTEND_BACKEND_PATH=/test
    ports:
      - "8001:3000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  sub-store-lab:
    image: ocyss/sub-store-lab:latest
    container_name: sub-store-lab
    restart: always
    volumes:
      - ./data:/opt/app/data
