services:
  sub-store:
    image: xream/sub-store:http-meta
    container_name: sub-store
    restart: always
    volumes:
    - ./data/sub-store-data:/opt/app/data
    environment:
    - SUB_STORE_FRONTEND_BACKEND_PATH=/backend // 自行随机生成
    ports:
    - "8001:3000"
  sub-store-lab:
    image: ghcr.io/ocyss/sub-store-lab:latest
    container_name: sub-store-lab
    restart: always
    env_file:
    - .env
    volumes:
    - ./data:/opt/app/data