services:
  sub-store:
    image: xream/sub-store:http-meta
    container_name: sub-store
    restart: always
    volumes:
      - ./data/sub-store-data:/opt/app/data
    environment:
      - SUB_STORE_FRONTEND_BACKEND_PATH=/test
    ports:
      - "8001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway" # use host.docker.internal:8000
    # network_mode: host